### ISSUE TITLE
Automatic Drift detection docs/example

### ISSUE THREAD

**Issue by jamengual** [cresta/atlantis-drift-detection#22]
Hi Guys.

In the doc you guys mention two workflows, one "Trigger a github workflow that can resolve the drift" and then the atlantis-drift-detection workflow but both are trigger on `workflow_distpatch`, so I was wondering what is the github action workflow to run this automatically?

I understand I could run in a cron every X minutes but do I wrong both workflows at the same time or just the drift action and I should expect to see a new PR created if drift was detected?

**Comment by jamengual** [comment]
mmm now that I started implementing I think I have figured out a few things:

the cron will run the `atlantis-drift-detection` every X time.
if the Atlantis API returns a nonempty plan it will then call the ` WORKFLOW_ID: trigger_undrifter.yaml` and create a PR to resolve the drift, I think.

The part that I do not understand is, what payload is sent to Atlantis to know which directory to plan against? how does the action determine which directory is the one it should be planned?

**Comment by cep21** [comment]
> the cron will run the atlantis-drift-detection every X time.

That is right.  maybe X = one day is right

> if the Atlantis API returns a nonempty plan it will then call the  WORKFLOW_ID: trigger_undrifter.yaml

That is correct

> create a PR to resolve the drift

Mostly.  It is up to the job itself to trigger a PR.  That part is dependent upon you, so it's hard for atlantis-drift-detection to automate that.

**Comment by jamengual** [comment]
Understood, I think the path that I'm following then is correct, thanks for confirming @cep21
